class_name EnemyRoster
extends RefCounted
## Enemy id -> look (model, textures, gear, clips, tints, extras) and its visual variants.
## Read through EnemyLooks (game/world/enemy_looks.gd), which builds the figures.
##
## A look is a dict; every key is optional except `model` (a Character.MODELS id):
##   model, texture (body atlas swap; regular families get theirs from SkinRules tiers, only
##   mini-bosses / bosses set it: their colourways are unique), tint + strength (0..1 blend
##   toward a colour), emission, scale (1 = a regular unit; mini-bosses ~1.5, bosses 1.6-1.8),
##   gear {slot: scene}, gear_xf {slot: [pos, rot_deg, scale]}, clips {role: clip | [clips]}
##   (roles: idle, attack, hit, death, spawn, walk, cheer, cast), undead (skeleton clip set),
##   ranged ("bolt" | "arrow" | "magic"), shot (projectile colour), parts {mesh-name fragment:
##   [tint, strength, emission?]}, hide [mesh-name fragments], extras [...], eyes (glow colour),
##   eyes_at (eye socket offset on the head bone), light, aura, cracks, ghost, pumpkin, hud
##   (extra HUD height for hats / crowns), label (gallery name), boss / miniboss.
## `variants`: COSMETIC override dicts merged over the base look (clips merged key by key,
## everything else replaced): weapons, accessories, body model. One is picked per spawn
## (EnemyLooks.variant_for), so a line of three skeleton minions shows three different
## skeletons and runs differ. Variants never carry meaning: colourways by tier, elite and
## trait visuals come from SkinRules (game/enemies/skin_rules.gd) on top.

const FOE := "res://assets/kaykit/foes/"
const SKW := FOE + "skeletons/weapons/"
const SKIN_B := FOE + "skeletons/textures/skeleton_texture_B.png"
const ADT := FOE + "adventurers/textures/"
const ADW := FOE + "adventurers/weapons/"
const ADV := "res://assets/kaykit/adventurers/weapons/"
const WPN := "res://assets/kaykit/weapons/"
const FWX := FOE + "weapons/"
const ORC := FOE + "monthly/orc/"
const WWF := FOE + "monthly/werewolf/"
const PAL := FOE + "monthly/paladin/"
const NIN := FOE + "monthly/ninja/"
const MON := FOE + "monthly/monster/"
const BONE := Color(0.94, 0.9, 0.8)
const ICE := Color(0.62, 0.84, 1.0)

## Clip sets by weapon style (Rig_Medium names; the Large rig's are listed separately).
const ONE_H := ["Melee_1H_Attack_Chop", "Melee_1H_Attack_Slice_Diagonal", "Melee_1H_Attack_Slice_Horizontal"]
const STAB := ["Melee_1H_Attack_Stab", "Melee_1H_Attack_Slice_Diagonal"]
const TWO_H := ["Melee_2H_Attack_Chop", "Melee_2H_Attack_Slice"]
const DUAL := ["Melee_Dualwield_Attack_Slice", "Melee_Dualwield_Attack_Chop", "Melee_Dualwield_Attack_Stab"]
const PUNCH := ["Melee_Unarmed_Attack_Punch_A", "Melee_Unarmed_Attack_Kick"]
const LARGE_2H := ["Melee_2H_Attack", "Melee_2H_Slam"]
const LARGE_1H := ["Melee_1H_Slash", "Melee_1H_Stab"]
const LARGE_FIST := ["Melee_Unarmed_Punch", "Melee_Unarmed_Smash"]

const LOOKS := {
	# --- crypt regulars: the real KayKit skeletons ------------------------------------------------
	"skeleton_minion": {"model": "skel_minion", "undead": true,
		"gear": {"handslot.r": SKW + "Skeleton_Blade.gltf"}, "clips": {"attack": ONE_H}, "label": "blade",
		"variants": [{},
			{"label": "axe + buckler",
				"gear": {"handslot.r": SKW + "Skeleton_Axe.gltf", "handslot.l": SKW + "Skeleton_Shield_Small_A.gltf"}},
			{"label": "twin daggers", "gear": {"handslot.r": SKW + "Skeleton_Dagger.gltf", "handslot.l": SKW + "Skeleton_Dagger.gltf"},
				"clips": {"attack": DUAL}},
			{"label": "bare bones", "gear": {},
				"clips": {"attack": PUNCH, "idle": "Melee_Unarmed_Idle"}}]},
	"skeleton_warrior": {"model": "skel_warrior", "undead": true,
		"gear": {"handslot.r": SKW + "Skeleton_Blade.gltf", "handslot.l": SKW + "Skeleton_Shield_Small_A.gltf"},
		"clips": {"attack": ONE_H}, "label": "blade + shield",
		"variants": [{},
			{"label": "axe + shield",
				"gear": {"handslot.r": SKW + "Skeleton_Axe.gltf", "handslot.l": SKW + "Skeleton_Shield_Small_B.gltf"}},
			{"label": "great mace", "gear": {"handslot.r": SKW + "Skeleton_Mace_Large.gltf"},
				"clips": {"attack": TWO_H, "idle": "Melee_2H_Idle"}},
			{"label": "bare-headed mace", "hide": ["Helmet"],
				"gear": {"handslot.r": SKW + "Skeleton_Mace.gltf", "handslot.l": SKW + "Skeleton_Shield_Small_A.gltf"}}]},
	"skeleton_archer": {"model": "skel_rogue", "undead": true, "ranged": "bolt",
		"gear": {"handslot.r": SKW + "Skeleton_Crossbow.gltf", "chest": SKW + "Skeleton_Quiver.gltf"},
		"gear_xf": {"chest": [Vector3(0.12, 0.25, -0.32), Vector3(0, 0, -25), 1.0]},
		"clips": {"attack": "Ranged_1H_Shoot", "idle": "Ranged_1H_Aiming"}, "label": "crossbow",
		"variants": [{},
			{"label": "crossbow + knife", "gear": {"handslot.r": SKW + "Skeleton_Crossbow.gltf", "handslot.l": SKW + "Skeleton_Dagger.gltf",
				"chest": SKW + "Skeleton_Quiver.gltf"}},
			{"model": "skel_minion", "label": "minion bowman", "ranged": "arrow",
				"gear": {"handslot.l": ADV + "bow_withString.gltf", "chest": SKW + "Skeleton_Quiver.gltf"},
				"clips": {"attack": "Ranged_Bow_Release", "idle": "Ranged_Bow_Idle"}},
			{"label": "hooded bowman", "ranged": "arrow",
				"gear": {"handslot.l": ADV + "bow_withString.gltf", "chest": SKW + "Skeleton_Quiver.gltf"},
				"clips": {"attack": "Ranged_Bow_Release", "idle": "Ranged_Bow_Idle"}}]},
	"cultist": {"model": "necromancer", "ranged": "magic", "shot": Color(0.7, 0.4, 1.0),
		"gear": {"handslot.r": SKW + "Skeleton_Staff.gltf"}, "hud": 0.25,
		"clips": {"attack": ["Ranged_Magic_Shoot", "Ranged_Magic_Spellcasting"], "cast": "Ranged_Magic_Spellcasting"},
		"label": "necromancer",
		"variants": [{},
			{"label": "necromancer (B)", "shot": Color(0.4, 1.0, 0.6),
				"gear": {"handslot.r": FWX + "staff_C.gltf"}},
			{"model": "mage", "label": "hedge witch", "hud": 0.35,
				"gear": {"handslot.r": FWX + "wand_B.gltf", "handslot.l": ADV + "spellbook_open.gltf"}},
			{"model": "skel_mage", "undead": true, "label": "skeleton mage", "hud": 0.35,
				"gear": {"handslot.r": SKW + "Skeleton_Staff.gltf"}}]},
	"bandit": {"model": "orc", "gear": {"handslot.r": ORC + "weapons/Orc_Axe.gltf.glb"}, "clips": {"attack": ONE_H},
		"label": "orc raider",
		"variants": [{},
			{"model": "ninja", "label": "ninja",
				"gear": {"handslot.r": NIN + "weapons/Ninja_Katana.gltf"}, "clips": {"attack": ["Melee_1H_Attack_Slice_Horizontal", "Melee_1H_Attack_Stab"]}},
			{"model": "rogue_hooded", "label": "cutthroat",
				"gear": {"handslot.r": WPN + "dagger_A.gltf", "handslot.l": WPN + "dagger_B.gltf"}, "clips": {"attack": DUAL}},
			{"label": "orc clubber",
				"gear": {"handslot.r": ORC + "weapons/Orc_Club.gltf.glb"}}]},
	"brute": {"model": "barbarian_large", "scale": 0.9,
		"gear": {"handslot.r": ADW + "axe_2handed_Large.gltf"}, "clips": {"attack": LARGE_2H, "idle": "Melee_2H_Idle"},
		"label": "great axe",
		"variants": [{},
			{"label": "axe + shield",
				"gear": {"handslot.r": ADW + "axe_1handed_Large.gltf", "handslot.l": ADW + "shield_round_barbarian_Large.gltf"},
				"clips": {"attack": LARGE_1H, "idle": "Idle_B"}},
			{"model": "skel_golem", "undead_large": true, "label": "bone golem",
				"gear": {"handslot.r": SKW + "Skeleton_Golem_Axe.gltf"}, "clips": {"attack": LARGE_1H, "idle": "Idle_B"}},
			{"label": "brawler", "gear": {},
				"clips": {"attack": LARGE_FIST, "idle": "Melee_Unarmed_Idle"}}]},
	# --- biome regulars ------------------------------------------------------------------------
	"thorn_sprite": {"model": "mannequin", "tint": Color(0.38, 0.64, 0.27), "strength": 0.92, "scale": 0.8,
		"emission": Color(0.01, 0.03, 0.0), "gear": {}, "clips": {"attack": PUNCH, "cast": "Ranged_Magic_Spellcasting"},
		"extras": ["leaf_crown", "leaf_shoulders", "leaf_motes"], "light": Color(0.5, 1.0, 0.4), "eyes": Color(1.0, 0.95, 0.5),
		"label": "leaf sprite", "hud": 0.2,
		"variants": [{},
			{"tint": Color(0.72, 0.5, 0.22), "label": "autumn sprite", "leaf": Color(0.9, 0.55, 0.2), "bloom": Color(1.0, 0.85, 0.3),
				"light": Color(1.0, 0.7, 0.3)},
			{"model": "druid", "tint": Color(0.4, 0.66, 0.3), "strength": 0.35,
				"label": "antlered druid", "gear": {"handslot.r": ADW + "druid_staff.gltf"}, "extras": ["leaf_shoulders", "leaf_motes"],
				"eyes": null, "clips": {"attack": ["Ranged_Magic_Shoot"]}, "hud": 0.45}]},
	"wolf_bandit": {"model": "werewolf", "gear": {"handslot.r": WWF + "weapons/axe.gltf"}, "clips": {"attack": ONE_H},
		"label": "wood-axe wolf", "hud": 0.15,
		"variants": [{},
			{"label": "twin-knife wolf",
				"gear": {"handslot.r": WPN + "dagger_A.gltf", "handslot.l": WPN + "dagger_A.gltf"}, "clips": {"attack": DUAL}},
			{"label": "clawed wolf",
				"gear": {"handslot.r": WPN + "fistweapon_A.gltf", "handslot.l": WPN + "fistweapon_A.gltf"},
				"clips": {"attack": PUNCH, "idle": "Melee_Unarmed_Idle"}}]},
	"hollow_wisp": {"model": "mannequin", "tint": Color(0.45, 1.0, 0.86), "strength": 0.92, "scale": 1.0,
		"gear": {}, "clips": {"attack": "Ranged_Magic_Shoot"}, "ghost": true, "ranged": "magic", "shot": Color(0.5, 1.0, 0.85),
		"extras": ["float", "wisp_trail"], "light": Color(0.4, 1.0, 0.85), "eyes": Color(0.8, 1.0, 0.95), "label": "teal wisp",
		"variants": [{},
			{"model": "skel_mage", "undead": true, "label": "ghost mage", "tint": Color(0.5, 1.0, 0.9), "hud": 0.35,
				"clips": {"attack": "Ranged_Magic_Shoot", "idle": "Idle_B"}, "eyes": null},
			{"model": "skel_minion", "undead": true, "label": "violet shade", "tint": Color(0.75, 0.55, 1.0),
				"light": Color(0.7, 0.45, 1.0), "shot": Color(0.8, 0.55, 1.0), "eyes": null,
				"clips": {"attack": "Ranged_Magic_Shoot", "idle": "Idle_B"}}]},
	"frost_skeleton": {"model": "skel_warrior", "undead": true, "tint": Color(0.72, 0.9, 1.0), "strength": 0.72,
		"emission": Color(0.04, 0.09, 0.16),
		"gear": {"handslot.r": SKW + "Skeleton_Axe.gltf", "handslot.l": SKW + "Skeleton_Shield_Small_B.gltf"},
		"clips": {"attack": ONE_H}, "extras": ["shoulder_ice", "frost_mist"], "label": "ice axe",
		"variants": [{},
			{"model": "skel_minion", "label": "rime blade", "gear": {"handslot.r": SKW + "Skeleton_Blade.gltf"},
				"extras": ["ice_crown", "frost_mist"]},
			{"hide": ["Helmet"], "label": "frost reaper", "gear": {"handslot.r": SKW + "Skeleton_Scythe.gltf"},
				"clips": {"attack": TWO_H, "idle": "Melee_2H_Idle"}}]},
	"ice_archer": {"model": "skel_rogue", "undead": true, "tint": Color(0.82, 0.94, 1.0), "strength": 0.72,
		"emission": Color(0.05, 0.1, 0.16), "ranged": "bolt", "shot": Color(0.6, 0.9, 1.0),
		"gear": {"handslot.r": SKW + "Skeleton_Crossbow.gltf"}, "clips": {"attack": "Ranged_1H_Shoot", "idle": "Ranged_1H_Aiming"},
		"extras": ["frost_mist"], "label": "ice crossbow",
		"variants": [{},
			{"model": "skel_minion", "ranged": "arrow", "label": "ice bowman",
				"gear": {"handslot.l": ADV + "bow_withString.gltf", "chest": SKW + "Skeleton_Quiver.gltf"},
				"gear_xf": {"chest": [Vector3(0.12, 0.25, -0.32), Vector3(0, 0, -25), 1.0]},
				"clips": {"attack": "Ranged_Bow_Release", "idle": "Ranged_Bow_Idle"}, "extras": ["ice_crown", "frost_mist"]},
			{"label": "crowned crossbow", "extras": ["shoulder_ice", "frost_mist"]}]},
	"bone_knight": {"model": "skel_warrior", "undead": true, "scale": 1.05,
		"gear": {"handslot.r": SKW + "Skeleton_Blade.gltf", "handslot.l": SKW + "Skeleton_Shield_Large_A.gltf"},
		"clips": {"attack": ONE_H, "idle": "Idle_A"}, "parts": {"Cloak": [Color(0.3, 0.12, 0.42), 0.85]},
		"label": "tower shield",
		"variants": [{},
			{"label": "mace + tower shield",
				"gear": {"handslot.r": SKW + "Skeleton_Mace.gltf", "handslot.l": SKW + "Skeleton_Shield_Large_B.gltf"}},
			{"label": "axe + tower shield", "parts": {"Cloak": [Color(0.12, 0.1, 0.14), 0.9]},
				"gear": {"handslot.r": SKW + "Skeleton_Axe.gltf", "handslot.l": SKW + "Skeleton_Shield_Large_B.gltf"}}]},
	"ember_imp": {"model": "mannequin", "tint": Color(0.2, 0.13, 0.12), "strength": 0.95, "scale": 0.75,
		"emission": Color(0.4, 0.11, 0.02), "cracks": Color(1.0, 0.45, 0.1, 1.0), "gear": {},
		"clips": {"attack": PUNCH, "cast": "Ranged_Magic_Spellcasting"}, "extras": ["horns", "head_flame"],
		"light": Color(1.0, 0.5, 0.15), "eyes": Color(1.0, 0.8, 0.3), "label": "cinder imp",
		"variants": [{},
			{"model": "monster", "tint": Color(0.75, 0.22, 0.06),
				"strength": 0.6, "emission": Color(0.3, 0.07, 0.0), "cracks": Color(1.0, 0.5, 0.1, 0.8), "eyes": null,
				"extras": ["head_flame"], "label": "fire newt"},
			{"tint": Color(0.16, 0.12, 0.2), "emission": Color(0.35, 0.05, 0.18), "cracks": Color(1.0, 0.3, 0.55, 1.0),
				"light": Color(1.0, 0.35, 0.6), "eyes": Color(1.0, 0.6, 0.85), "label": "brimstone imp"}]},
	"magma_brute": {"model": "skel_golem", "undead_large": true, "tint": Color(0.14, 0.12, 0.13), "strength": 0.8,
		"scale": 1.1, "cracks": Color(1.0, 0.42, 0.08, 1.0), "gear": {"handslot.r": SKW + "Skeleton_Golem_Axe.gltf"},
		"clips": {"attack": LARGE_1H, "idle": "Idle_B"}, "extras": ["embers"], "light": Color(1.0, 0.45, 0.12),
		"label": "basalt golem",
		"variants": [{},
			{"model": "barbarian_large", "undead_large": false, "strength": 0.85,
				"label": "magma ogre", "gear": {"handslot.r": WPN + "hammer_B.gltf"}, "eyes": Color(1.0, 0.7, 0.2),
				"clips": {"attack": LARGE_2H, "idle": "Melee_2H_Idle"}},
			{"model": "mannequin_large", "undead_large": false, "strength": 0.95, "gear": {}, "clips": {"attack": LARGE_FIST},
				"eyes": Color(1.0, 0.7, 0.2), "label": "lava hulk"}]},
	# --- 2026-09-28 roster (docs/design/2026-09-28-classes-enemies-skins.md §3) --------------------
	"bone_cutthroat": {"model": "skel_rogue", "undead": true,
		"gear": {"handslot.r": SKW + "Skeleton_Dagger.gltf", "handslot.l": SKW + "Skeleton_Dagger.gltf"},
		"clips": {"attack": DUAL}, "label": "twin daggers",
		"variants": [{},
			{"label": "dagger + buckler", "gear": {"handslot.r": SKW + "Skeleton_Dagger.gltf", "handslot.l": SKW + "Skeleton_Shield_Small_B.gltf"},
				"clips": {"attack": STAB}},
			{"label": "bare-skull knives", "hide": ["Hood"],
				"gear": {"handslot.r": WPN + "dagger_B.gltf", "handslot.l": SKW + "Skeleton_Dagger.gltf"}},
			{"label": "skull scythe", "gear": {"handslot.r": SKW + "Skeleton_Scythe.gltf"},
				"clips": {"attack": TWO_H, "idle": "Melee_2H_Idle"}}]},
	"bone_golem": {"model": "skel_golem", "undead_large": true, "scale": 1.05,
		"gear": {"handslot.r": SKW + "Skeleton_Golem_Axe.gltf"}, "clips": {"attack": LARGE_1H, "idle": "Idle_B"},
		"label": "skull axe",
		"variants": [{},
			{"label": "great skull axe", "gear": {"handslot.r": SKW + "Skeleton_Golem_Axe_Large.gltf"},
				"clips": {"attack": LARGE_2H, "idle": "Melee_2H_Idle"}},
			{"label": "axe + tower shield",
				"gear": {"handslot.r": SKW + "Skeleton_Golem_Axe.gltf", "handslot.l": SKW + "Skeleton_Shield_Large_B.gltf"},
				"gear_xf": {"handslot.l": [Vector3.ZERO, Vector3.ZERO, 1.8]}},
			{"label": "bone fists", "gear": {}, "extras": ["bone_pauldrons"],
				"clips": {"attack": LARGE_FIST, "idle": "Melee_Unarmed_Idle"}}]},
	"orc_raider": {"model": "orc", "gear": {"handslot.r": ORC + "weapons/Orc_Axe.gltf.glb"}, "clips": {"attack": ONE_H},
		"label": "orc axe",
		"variants": [{},
			{"label": "twin axes", "gear": {"handslot.r": ORC + "weapons/Orc_Axe.gltf.glb", "handslot.l": ORC + "weapons/Orc_Axe.gltf.glb"},
				"clips": {"attack": DUAL}},
			{"label": "club, no pack", "hide": ["Warpack"], "gear": {"handslot.r": ORC + "weapons/Orc_Club.gltf.glb"}},
			{"label": "axe + horn", "gear": {"handslot.r": ORC + "weapons/Orc_Axe.gltf.glb", "handslot.l": ORC + "weapons/Orc_DrinkingHorn.gltf.glb"}}]},
	# the war drum rides on the belly (chest socket) and the stick beats it (attack clips = drum beats)
	"orc_drummer": {"model": "orc", "hide": ["Warpack"],
		"gear": {"handslot.r": ORC + "weapons/Orc_WardrumStick.gltf.glb", "chest": ORC + "weapons/Orc_Wardrum.gltf.glb"},
		"gear_xf": {"chest": [Vector3(0, -0.08, 0.36), Vector3(70, 0, 0), 0.58]},
		"clips": {"attack": ONE_H, "cheer": "Melee_1H_Attack_Chop", "cast": "Melee_1H_Attack_Chop"}, "drum": true,
		"label": "belly drum",
		"variants": [{},
			{"label": "drum + axe", "gear": {"handslot.r": ORC + "weapons/Orc_Axe.gltf.glb", "handslot.l": ORC + "weapons/Orc_WardrumStick.gltf.glb",
				"chest": ORC + "weapons/Orc_Wardrum.gltf.glb"}},
			{"label": "drum on the back", "hide": [],
				"gear": {"handslot.r": ORC + "weapons/Orc_WardrumStick.gltf.glb", "handslot.l": ORC + "weapons/Orc_WardrumStick.gltf.glb",
					"chest": ORC + "weapons/Orc_Wardrum.gltf.glb"},
				"gear_xf": {"chest": [Vector3(0, 0.3, -0.52), Vector3(90, 0, 0), 0.75]}, "clips": {"attack": DUAL, "cheer": "Melee_Dualwield_Attack_Chop"}}]},
	# transform: `forms` overrides merge over the variant when the enemy changes form (Werewolf_Man
	# -> Werewolf_Wolf, an in-place model swap on enemy_transformed; tier_key keeps the man's colourway)
	"werewolf": {"model": "werewolf_man", "tier_key": "werewolf_man",
		"gear": {"handslot.r": WWF + "weapons/axe.gltf"}, "clips": {"attack": ONE_H}, "label": "woodsman",
		"forms": {"wolf": {"model": "werewolf", "gear": {"handslot.r": WPN + "fistweapon_A.gltf", "handslot.l": WPN + "fistweapon_A.gltf"},
			"clips": {"attack": PUNCH, "idle": "Melee_Unarmed_Idle"}, "eyes": Color(1.0, 0.82, 0.3), "eyes_at": Vector3(0, 0.02, 0.06)}},
		"variants": [{},
			{"label": "woodsman (axe + knife)", "gear": {"handslot.r": WWF + "weapons/axe.gltf", "handslot.l": WPN + "dagger_A.gltf"},
				"clips": {"attack": DUAL}},
			{"label": "hunter (spear)", "gear": {"handslot.r": WPN + "spear_A.gltf"}, "clips": {"attack": STAB}}]},
	"fallen_paladin": {"model": "paladin_helm", "tint": Color(0.2, 0.13, 0.3), "strength": 0.8,
		"emission": Color(0.04, 0.0, 0.07), "gear": {"handslot.r": PAL + "weapons/paladin_hammer.gltf", "handslot.l": PAL + "weapons/paladin_shield.gltf"},
		"clips": {"attack": ONE_H}, "parts": {"Cape": [Color(0.3, 0.06, 0.36), 0.9]}, "light": Color(0.7, 0.4, 1.0),
		"eyes": Color(0.8, 0.45, 1.0), "eyes_at": Vector3(0, 0.08, 0.06), "hud": 0.3,
		"label": "oathbreaker",
		"variants": [{},
			{"label": "black sword", "gear": {"handslot.r": WPN + "sword_E.gltf", "handslot.l": PAL + "weapons/paladin_shield.gltf"}},
			{"label": "great sword", "gear": {"handslot.r": ADV + "sword_2handed.gltf"}, "clips": {"attack": TWO_H, "idle": "Melee_2H_Idle"}}]},
	# --- mini-bosses: ~1.6x a regular (1.25x the Large-rig brute), lit by an aura -----------------
	# (scale is the body multiplier; Large-rig bodies are already ~1.42x a regular, see hud_height)
	"mini_pumpkin_knight": {"model": "knight", "texture": ADT + "knight_texture_alt_C.png", "tint": Color(0.22, 0.16, 0.14),
		"strength": 0.35, "scale": 1.6, "emission": Color(0.1, 0.03, 0.0),
		"gear": {"handslot.r": ADV + "sword_2handed_color.gltf", "handslot.l": ADV + "shield_spikes_color.gltf"},
		"clips": {"attack": ["Melee_2H_Attack_Chop", "Melee_1H_Attack_Slice_Diagonal"]},
		"pumpkin": true, "pumpkin_scale": 0.8, "aura": Color(1.0, 0.5, 0.12), "miniboss": true, "label": "black knight",
		"variants": [{},
			{"model": "paladin", "texture": PAL + "textures/paladin_texture_B.png", "strength": 0.3, "label": "fallen paladin",
				"gear": {"handslot.r": PAL + "weapons/paladin_hammer.gltf", "handslot.l": ADV + "shield_spikes_color.gltf"}}]},
	"mini_bone_champion": {"model": "skel_golem", "undead_large": true, "scale": 1.15, "tint": BONE, "strength": 0.2,
		"gear": {"handslot.r": SKW + "Skeleton_Golem_Axe_Large.gltf"}, "clips": {"attack": LARGE_2H, "idle": "Melee_2H_Idle"},
		"eyes_glow": Color(0.55, 0.85, 1.0), "extras": ["bone_pauldrons"], "aura": Color(0.75, 0.85, 1.0), "miniboss": true,
		"label": "golem champion",
		"variants": [{},
			{"texture": SKIN_B, "eyes_glow": Color(1.0, 0.7, 0.3), "label": "golem champion (B)",
				"gear": {"handslot.r": SKW + "Skeleton_Golem_Axe.gltf", "handslot.l": SKW + "Skeleton_Shield_Large_A.gltf"},
				"gear_xf": {"handslot.l": [Vector3.ZERO, Vector3.ZERO, 1.8]}, "clips": {"attack": LARGE_1H, "idle": "Idle_B"}}]},
	# the skeleton Necromancer body, texture B (black robes), keeping its staff, book and green aura
	"mini_grave_mage": {"model": "necromancer", "texture": SKIN_B, "scale": 1.6, "tint": Color(0.2, 0.55, 0.35), "strength": 0.22,
		"emission": Color(0.01, 0.06, 0.03), "gear": {"handslot.r": SKW + "Skeleton_Staff.gltf", "handslot.l": ADV + "spellbook_open.gltf"},
		"clips": {"attack": ["Ranged_Magic_Spellcasting", "Ranged_Magic_Shoot"], "cast": "Ranged_Magic_Summon"},
		"ranged": "magic", "shot": Color(0.4, 1.0, 0.55), "extras": ["hand_flame_green", "grave_candles"],
		"aura": Color(0.35, 1.0, 0.55), "miniboss": true, "hud": 0.25, "label": "grave necromancer",
		"variants": [{},
			{"strength": 0.2, "gear": {"handslot.r": SKW + "Skeleton_Scythe.gltf", "handslot.l": ADV + "spellbook_open.gltf"}, "label": "reaper necromancer",
				"clips": {"attack": ["Ranged_Magic_Spellcasting", "Melee_2H_Attack_Slice"]}}]},
	"mini_frost_warden": {"model": "paladin_helm", "tint": Color(0.74, 0.9, 1.0), "strength": 0.82, "scale": 1.6,
		"emission": Color(0.06, 0.13, 0.22), "gear": {"handslot.r": PAL + "weapons/paladin_hammer.gltf", "handslot.l": PAL + "weapons/paladin_shield.gltf"},
		"clips": {"attack": ONE_H}, "parts": {"Cape": [Color(0.9, 0.96, 1.0), 0.9]},
		"extras": ["ice_crown", "shoulder_ice", "frost_mist"], "eyes": Color(0.6, 0.95, 1.0), "eyes_at": Vector3(0, 0.08, 0.06),
		"aura": Color(0.55, 0.88, 1.0), "miniboss": true, "hud": 0.3, "label": "frost paladin",
		"variants": [{},
			{"model": "knight", "texture": ADT + "knight_texture_alt_A.png", "strength": 0.65, "label": "frost knight",
				"gear": {"handslot.r": ADV + "sword_2handed_color.gltf"}, "clips": {"attack": TWO_H}, "eyes_at": Vector3.ZERO}]},
	"mini_briar_beast": {"model": "werewolf", "tint": Color(0.34, 0.5, 0.22), "strength": 0.78, "scale": 1.65,
		"gear": {"handslot.r": WPN + "fistweapon_B.gltf", "handslot.l": WPN + "fistweapon_B.gltf"},
		"clips": {"attack": PUNCH, "idle": "Melee_Unarmed_Idle", "cast": "Ranged_Magic_Summon"},
		"extras": ["thorns_front", "leaf_shoulders", "leaf_motes"],
		"eyes": Color(1.0, 0.85, 0.3), "eyes_at": Vector3(0, 0.02, 0.06), "aura": Color(0.55, 1.0, 0.35), "miniboss": true,
		"label": "moss werewolf",
		"variants": [{},
			{"texture": WWF + "textures/werewolf_B.png", "tint": Color(0.42, 0.34, 0.2), "label": "bramble werewolf"}]},
	"mini_cinder_brute": {"model": "orc", "texture": ORC + "textures/orc_texture_B.png", "tint": Color(0.14, 0.1, 0.1),
		"strength": 0.7, "scale": 1.6, "cracks": Color(1.0, 0.45, 0.1, 1.0), "gear": {"handslot.r": WPN + "hammer_B.gltf"},
		"clips": {"attack": TWO_H, "idle": "Melee_2H_Idle"}, "extras": ["embers", "shoulder_flames"], "eyes": Color(1.0, 0.75, 0.2),
		"aura": Color(1.0, 0.45, 0.12), "miniboss": true, "label": "cinder orc",
		"variants": [{},
			{"texture": "", "tint": Color(0.2, 0.12, 0.08), "gear": {"handslot.r": ORC + "weapons/Orc_Club.gltf.glb"},
				"clips": {"attack": ONE_H, "idle": "Idle_B"}, "label": "cinder orc (club)"}]},
	"mini_moonfang": {"model": "werewolf_man", "texture": WWF + "textures/werewolf_B.png", "scale": 1.6,
		"gear": {"handslot.r": WWF + "weapons/axe.gltf"}, "gear_xf": {"handslot.r": [Vector3.ZERO, Vector3.ZERO, 1.25]},
		"clips": {"attack": ONE_H, "cast": "Ranged_Magic_Spellcasting"},
		"aura": Color(0.78, 0.86, 1.0), "extras": ["moon_motes"], "miniboss": true, "label": "silver moonfang",
		"forms": {"wolf": {"model": "werewolf", "gear": {"handslot.r": WPN + "fistweapon_B.gltf", "handslot.l": WPN + "fistweapon_B.gltf"},
			"gear_xf": {}, "clips": {"attack": PUNCH, "idle": "Melee_Unarmed_Idle"}, "eyes": Color(0.7, 0.95, 1.0), "eyes_at": Vector3(0, 0.02, 0.06)}},
		"variants": [{},
			{"tint": Color(0.55, 0.6, 0.75), "strength": 0.25, "label": "moonfang (blue)",
				"gear": {"handslot.r": WPN + "halberd.gltf"}, "gear_xf": {}, "clips": {"attack": TWO_H, "idle": "Melee_2H_Idle"}}]},
	"mini_orc_warchief": {"model": "orc", "texture": ORC + "textures/orc_texture_B.png", "scale": 1.6, "hide": ["Warpack"],
		"gear": {"handslot.r": ORC + "weapons/Orc_Club.gltf.glb", "chest": ORC + "weapons/Orc_Wardrum.gltf.glb"},
		"gear_xf": {"chest": [Vector3(0, 0.3, -0.52), Vector3(90, 0, 0), 0.75]},
		"clips": {"attack": ONE_H, "cast": "Ranged_Magic_Summon", "cheer": "Melee_1H_Attack_Chop"}, "drum": true,
		"eyes": Color(1.0, 0.55, 0.2), "aura": Color(1.0, 0.55, 0.25), "extras": ["war_banner"], "miniboss": true, "label": "club + war drum",
		"variants": [{},
			{"tint": Color(0.3, 0.18, 0.12), "strength": 0.35, "label": "warchief (axe)",
				"gear": {"handslot.r": ORC + "weapons/Orc_Axe.gltf.glb", "handslot.l": ORC + "weapons/Orc_Axe.gltf.glb", "chest": ORC + "weapons/Orc_Wardrum.gltf.glb"},
				"clips": {"attack": DUAL}}]},
	# --- bosses: ~1.9x a regular (Large rigs 1.35 = ~1.9x; the Magma Golem towers at 1.8 x Large) -----
	"boss_bone_warden": {"model": "paladin_helm", "texture": PAL + "textures/paladin_texture_B.png", "tint": BONE,
		"strength": 0.72, "scale": 1.9, "emission": Color(0.03, 0.0, 0.05),
		"gear": {"handslot.r": WPN + "sword_E.gltf", "handslot.l": PAL + "weapons/paladin_shield.gltf"},
		"clips": {"attack": ONE_H, "cast": "Ranged_Magic_Summon"}, "parts": {"Cape": [Color(0.32, 0.1, 0.45), 0.92]},
		"extras": ["bone_pauldrons", "skull_crest"], "eyes": Color(0.85, 0.5, 1.0), "eyes_at": Vector3(0, 0.0, 0.12),
		"light": Color(0.7, 0.4, 1.0), "boss": true, "hud": 0.3, "label": "bone paladin",
		"variants": [{},
			{"texture": "", "tint": Color(0.86, 0.84, 0.8), "label": "bone paladin (gold trim)"}]},
	"boss_hollow_king": {"model": "barbarian", "texture": ADT + "barbarian_texture_alt_C.png", "tint": Color(0.45, 0.3, 0.22),
		"strength": 0.2, "scale": 1.8, "gear": {"handslot.r": ADV + "axe_2handed.gltf"}, "clips": {"attack": TWO_H},
		"boss": true, "pumpkin": true, "label": "hollow king"},
	"boss_lich": {"model": "skel_mage", "undead": true, "tint": Color(0.5, 0.28, 0.85), "strength": 0.45, "scale": 1.9,
		"emission": Color(0.12, 0.04, 0.22), "gear": {"handslot.r": SKW + "Skeleton_Staff.gltf"},
		"gear_xf": {"handslot.r": [Vector3.ZERO, Vector3.ZERO, 1.3]},
		"clips": {"attack": ["Ranged_Magic_Spellcasting", "Ranged_Magic_Shoot"], "idle": "Idle_B", "cast": "Ranged_Magic_Summon"},
		"ranged": "magic", "shot": Color(0.7, 0.4, 1.0), "boss": true, "glow": true, "eyes_glow": Color(0.6, 1.0, 0.95),
		"extras": ["crown", "motes"], "mote": Color(0.75, 0.45, 1.0), "light": Color(0.7, 0.4, 1.0), "hide": ["Hat"],
		"label": "crowned lich",
		"variants": [{},
			{"texture": SKIN_B, "tint": Color(0.35, 0.3, 0.9), "label": "lich (B)"}]},
	"boss_cinder_king": {"model": "barbarian_large", "texture": ADT + "barbarian_texture_alt_C.png", "tint": Color(0.2, 0.12, 0.1),
		"strength": 0.6, "scale": 1.35, "emission": Color(0.12, 0.03, 0.0), "cracks": Color(1.0, 0.5, 0.12, 0.8),
		"gear": {"handslot.r": ADW + "axe_2handed_Large.gltf"}, "clips": {"attack": LARGE_2H, "idle": "Melee_2H_Idle"},
		"extras": ["crown", "head_flame", "shoulder_flames", "embers"], "eyes": Color(1.0, 0.8, 0.3), "hide": ["BearHat"],
		"light": Color(1.0, 0.5, 0.15), "boss": true, "label": "cinder king",
		"variants": [{},
			{"texture": ADT + "barbarian_texture_alt_A.png", "strength": 0.7, "label": "cinder king (A)",
				"gear": {"handslot.r": WPN + "hammer_C.gltf"}}]},
	"boss_magma_golem": {"model": "mannequin_large", "tint": Color(1.0, 0.42, 0.1), "strength": 0.85, "scale": 1.8,
		"emission": Color(0.7, 0.2, 0.02), "cracks": Color(1.0, 0.8, 0.35, 0.8), "gear": {}, "clips": {"attack": LARGE_FIST},
		"extras": ["rock_shell", "embers"], "eyes": Color(1.0, 0.85, 0.4), "eyes_offset": Vector3(0, 0.02, 0.12),
		"hide": ["MannequinLarge_Head"], "light": Color(1.0, 0.45, 0.12), "boss": true, "label": "magma golem"},
}
