class_name UiIcons
extends RefCounted
## Drawn icon set (ui/icons/*.svg, generated by ui/icons/gen_icons.py).
## SVGs use #FFFFFF as the tint slot; tex() rasterises them at the requested pixel size with
## the tint substituted, so icons stay crisp at every size. Results are cached.
##
##   UiIcons.tex("heart", 48)                    # default colour for that icon
##   UiIcons.tex("rune_frost", 64, Color.WHITE)  # explicit tint
##   UiIcons.rect("coin", 40)                    # ready-made TextureRect
##   UiIcons.rect("3d:coins", 40)                # rendered prop (RenderedIcons), glyph fallback

const DIR := "res://ui/icons/"
const TINT_SLOT := "#FFFFFF"

## Default tint per icon (anything missing falls back to TEXT).
const DEFAULT := {
	"heart": UiPalette.HP, "coin": UiPalette.COIN, "shield": UiPalette.BLOCK, "sword": Color("e8e4f0"),
	"poison": UiPalette.POISON, "snowflake": UiPalette.FROST, "flame": Color("ff8a3a"), "bolt": Color("ffd84a"),
	"skull": Color("efe6d4"), "curse": UiPalette.CURSE, "dice": UiPalette.DIE_BODY, "star": UiPalette.GOLD_BRIGHT,
	"xp": UiPalette.XP, "reroll": UiPalette.TEXT, "crown": UiPalette.GOLD, "trophy": UiPalette.GOLD,
	"potion": UiPalette.HP_BRIGHT, "anvil": Color("aab4c8"), "portal": Color("a56bff"), "chest": UiPalette.GOLD,
	"campfire": Color("ff9a3a"), "flag": UiPalette.GOLD, "axe": Color("d8d2e2"), "staff": Color("8fd0ff"),
	"dagger": Color("d8d2e2"), "mirror": Color("9ad8f0"), "up": UiPalette.HEAL,
}

static var _cache: Dictionary = {}
static var _src: Dictionary = {}


static func exists(icon: String) -> bool:
	return FileAccess.file_exists(DIR + icon + ".svg")


static func default_color(icon: String) -> Color:
	if icon.begins_with("rune_"):
		return UiPalette.rune_color(icon.substr(5))
	if icon.begins_with("biome_"):
		return UiPalette.biome_color(icon.substr(6))
	if icon.begins_with("trait_"):
		var tk := icon.substr(6)
		if UiPalette.TRAIT.has(tk):
			return UiPalette.TRAIT[tk][1]
	if icon.begins_with("intent_"):
		var k := icon.substr(7)
		if UiPalette.INTENT.has(k):
			return UiPalette.INTENT[k][1]
	return DEFAULT.get(icon, UiPalette.TEXT)


static func tex(icon: String, px: int = 48, tint: Variant = null) -> Texture2D:
	if icon.begins_with("3d:"):
		# rendered 3D prop (ui/icons/rendered), or its vector stand-in when not rendered
		var rt := RenderedIcons.texture_at(icon.substr(3), px)
		return rt if rt != null else tex(RenderedIcons.fallback(icon.substr(3)), px, tint)
	var c: Color = tint if tint is Color else default_color(icon)
	var key := "%s|%d|%s" % [icon, px, c.to_html()]
	if _cache.has(key):
		return _cache[key]
	var src := _source(icon)
	if src == "":
		return null
	var svg := src.replace(TINT_SLOT, "#" + c.to_html(false))
	var img := Image.new()
	var err := img.load_svg_from_string(svg, float(px) / 24.0)
	if err != OK:
		push_error("UiIcons: cannot rasterise %s" % icon)
		return null
	img.generate_mipmaps()
	var t := ImageTexture.create_from_image(img)
	_cache[key] = t
	return t


static func _source(icon: String) -> String:
	if _src.has(icon):
		return _src[icon]
	var path := DIR + icon + ".svg"
	var s := ""
	if FileAccess.file_exists(path):
		s = FileAccess.get_file_as_string(path)
	else:
		push_error("UiIcons: missing icon %s" % icon)
	_src[icon] = s
	return s


## TextureRect showing an icon at `px` (logical px), centred and aspect-kept.
static func rect(icon: String, px: int = 48, tint: Variant = null) -> TextureRect:
	var r := TextureRect.new()
	r.texture = tex(icon, px * 2, tint) # 2x for crispness on retina / scaled canvases
	r.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	r.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	r.custom_minimum_size = Vector2(px, px)
	r.mouse_filter = Control.MOUSE_FILTER_IGNORE
	return r


static func rune_icon(rune: String) -> String:
	return "rune_" + rune


static func intent_icon(kind: String) -> String:
	return String(UiPalette.INTENT.get(kind, ["intent_aim"])[0])


static func biome_icon(id: String) -> String:
	return "biome_" + id if exists("biome_" + id) else "flag"


static func class_icon(class_id: String) -> String:
	return {"knight": "shield", "barbarian": "axe", "mage": "staff", "rogue": "dagger"}.get(class_id, "sword")
